# Generated by Django 5.2.5 on 2025-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#3b82f6', 'Blue'), ('#10b981', 'Green'), ('#f59e0b', 'Yellow'), ('#ef4444', 'Red'), ('#8b5cf6', 'Purple'), ('#ec4899', 'Pink')], default='#3b82f6', max_length=10),
        ),
    ]
